accounts/urls.py
from django.urls import path
from accounts.views import *
app_name='accounts'
urlpatterns = [
    path('',user_detail,name='user-detail-pk'),
    path("auth/users/<int:pk>", user_detail,name = 'user-detail-pk'),
    path("parties", user_detail,name = 'user-detail'),
    path('manage_party',manage_party,name='manage-party'),
    path('save_party',save_party,name='save-party'),
    path('manage_party/<int:pk>',manage_party,name='manage-party-pk'),
    path('delete_party/<int:pk>',delete_party,name='delete-party'),
    path('manage_transaction/<int:pk>/',manage_transaction,name='manage-transaction'),
    path('manage_transaction/',manage_transaction,name='manage-transaction'),
    path('save_transactions/', save_transaction, name='save-transaction'),
    path('transactions_list/',transaction_list, name='transaction_list'),
    path('delete_transaction/<int:pk>/', delete_transaction, name='delete-transaction'),
    path('view_transactions/<int:pk>', view_transactions, name='view-transactions'),
    path('manage_sales_purchase',manage_sales_purchases,name='manage-sales-purchase'),
    path('manage_sales_purchase/<int:pk>/',manage_sales_purchases,name='manage-sales-purchase'),
    path('save_trade',save_trade,name="save-trade"),
    path('sales_list/',sales_list, name='sales_list'),
    path('purchases_list/',purchases_list, name='purchases_list'),
    path('products/',products,name="products"),
    path('products/<int:pk>',products,name="products-pk"),
    path('manage_products/',manage_products,name="manage-products"),
    path('manage_products/<int:pk>',manage_products,name="manage-products-pk"),
    path('save_products/',save_product,name="save-product"),
    path('delete_product/<int:pk>',delete_product,name="delete-product"),
    path('print/<int:pk>',print_veiw,name="print-view-pk"),
]

core/urls.py
from django.urls import path
from core.views import *
app_name = 'core'
urlpatterns = [
    path('login/',login_page,name='login-page'),
    path('logout/',logout_user,name='logout'),
    path('user_login/',login_user,name='login-user'),
    path("users/", users_list,name = 'user-list'),
    path('save_user',save_user,name='save-user'),
    path('manage_user',manage_user,name='manage-user'),
    path('manage_user/<int:pk>',manage_user,name='manage-user-pk'),
    path('delete_user/<int:pk>',delete_user,name='delete-user'),
]

accounts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db.models import Count,Q
from django.core.exceptions import ValidationError

class Party(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    balance = models.BigIntegerField(default=0)
    name = models.CharField(max_length=255)
    phone_number = models.CharField(max_length=255,blank=True,null=True)
    address = models.CharField(max_length=255,blank=True,null=True)
    delete_flag = models.IntegerField(default=0)
    
    def __str__(self):
        return f'{self.name}'

    class Meta:
        unique_together = ['user','name']

    def clean(self):
        if (self.user.staffuser if hasattr(self.user, 'staffuser') else False) or self.user.is_superuser:
            raise ValidationError("A staff user cannot be associated with a party.")
        super().clean()
        
    def get_total_debit(self):
        transactions = self.transaction_set.filter(delete_flag=0)
        total_debit = sum(transaction.debit for transaction in transactions)
        return total_debit

    def get_total_credit(self):
        transactions = self.transaction_set.filter(delete_flag=0)
        total_credit = sum(transaction.credit for transaction in transactions)
        return total_credit
    def get_balance(self):
        total_debit = self.get_total_debit()
        total_credit = self.get_total_credit()
        balance = total_debit - total_credit
        return balance

class Form(models.Model):
    created_at = models.DateField(unique=True)
    
class Product(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    quantity = models.PositiveIntegerField()
    delete_flag = models.IntegerField(default=0)
    def __str__(self) -> str:
        return self.name
    
    def save(self, *args, **kwargs):
        self.name = self.name.lower()
        super().save(*args, **kwargs)
    
    class Meta:
        unique_together = ['user','name']
class Transaction(models.Model):
    party = models.ForeignKey(Party,on_delete=models.CASCADE)
    description = models.TextField(blank=True,null=True)
    debit = models.PositiveIntegerField(default=0)
    credit = models.PositiveIntegerField(default=0)
    time = models.TimeField(auto_now_add=True)
    form = models.ForeignKey(Form,on_delete = models.CASCADE)
    delete_flag = models.IntegerField(default=0)
    bill_number = models.PositiveIntegerField(default=0)
    discount = models.PositiveIntegerField(default=0)
    charges = models.PositiveIntegerField(default=0)
    is_sales = models.BooleanField(null=True,blank=True)

    def __str__(self):
        return self.party.name  
    
    class Meta:
        permissions = (
            ("can_manage_transactions","Can Manage Transactions"),
            ("can_manage_sales","Can Manage Sales"),
            ("can_manage_purchase","Can Manage Purchase"),
            ("can_manage_s_p","Can Manage Sale/Purchase"),

        )

    def get_running_balance(self):
        prior_transactions = Transaction.objects.filter(
            Q(form__created_at__lt=self.form.created_at) | (Q(form__created_at=self.form.created_at, time__lt=self.time)),
            delete_flag=0,
            party=self.party,
        )
        prior_debit = sum(transaction.debit for transaction in prior_transactions)
        prior_credit = sum(transaction.credit for transaction in prior_transactions)

        running_balance = prior_debit - prior_credit
        return running_balance + self.debit - self.credit
    


class TradeItem(models.Model):

    trade = models.ForeignKey(Transaction,on_delete=models.CASCADE,related_name='trade_items') 
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    price = models.PositiveIntegerField()
    delete_flag = models.IntegerField(default=0)
    def __str__(self) -> str:
        return f"{self.trade} - {self.product}"

accounts/forms.py
from django import forms
from accounts import models
from django.core.validators import RegexValidator
from django.contrib.auth.forms import UserCreationForm,PasswordChangeForm, UserChangeForm,PasswordResetForm
from django.contrib.auth import  get_user_model
from django.shortcuts import get_object_or_404
from django.db.models import Q  # Add this import
from django.db import IntegrityError

class SaveParty(forms.ModelForm):
    name = forms.CharField(max_length=255,required=True)
    address = forms.TextInput()
    pakistan_phone_validator = RegexValidator(
        regex=r'^(?:(?:\+92)|(?:0))(?:(?:3[0-9]{9})|(?:[1-9][0-9]{9}))$',
        message='Enter a valid phone number.',
    )
    phone_number = forms.CharField(
        label='Phone Number',
        validators=[pakistan_phone_validator],
        required=False
    )
    class Meta:
        model = models.Party
        fields = ['user', 'name', 'phone_number', 'address']

class SaveForm(forms.ModelForm):
    description = forms.TextInput()
    debit = forms.IntegerField(required=False)
    credit = forms.IntegerField(required=False)
    form = forms.IntegerField(required=False)
    party = forms.IntegerField(required=False)
    class Meta:
        model = models.Transaction
        fields = ['description','debit','credit','party','form']
    

accounts/views.py
import json
from django.db import transaction
from django.db.models import Max
from django.core import serializers
from django.core.exceptions import PermissionDenied
from django.db.models import BooleanField, Case, When, Value,F
from django.views.generic import ListView
from django.shortcuts import render,redirect,get_object_or_404
from django.http import JsonResponse ,HttpResponse,HttpResponseForbidden
from django.contrib import messages 
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth import update_session_auth_hash,logout,authenticate,login,get_user_model
from django.contrib.auth.decorators import login_required
from .models import *
from .forms import *
# Create your views here.
User = get_user_model()
def context_data(request):
    fullpath = request.get_full_path()
    abs_uri = request.build_absolute_uri()
    abs_uri = abs_uri.split(fullpath)[0]
    context = {
        'system_host': abs_uri,
        'page_name':'',
        'page_title':'',
        'system_name' : 'Accounts Managament System',
        'topbar':True,
        'footer':True,
    }
    return context

@login_required
def user_detail(request, pk=None):
    context = context_data(request)
    context['page'] = 'parties'
    context['page_title'] = 'Parties'
    options = []

    if pk:
        try:
            user = User.objects.get(pk=pk)
            if (user.assigned_staff.user if hasattr(user.assigned_staff, 'user') else None)==request.user or request.user.is_superuser:
                context['parties'] = Party.objects.select_related('user').filter(user = user)
                context['page_name'] = user
                context['user'] = user
                options.append(('product','Product')) 
                options.append(('manage_transactions','Manage Transactions')) 
                options.append(('manage_s_p','Manage Sale/purchases')) 
            else:
                return redirect('accounts:user-detail')
        except User.DoesNotExist:
            return HttpResponse(status=204)
    else:
        if (request.user.staffuser if hasattr(request.user, 'staffuser') else False) or request.user.is_superuser:
                return HttpResponse(status=204)
        context['parties'] = Party.objects.filter(user = request.user)
        context['page_name'] = request.user
        context['user'] = request.user
        options.append(('product','Product')) 
        options.append(('manage_transactions','Manage Transactions')) if request.user.has_perm('accounts.can_manage_transactions') else None
        options.append(('manage_s_p','Manage Sale/purchases')) if request.user.has_perm('accounts.can_manage_s/p') else None
    context['options'] = options
    return render(request,'accounts/party.html',context)

@login_required
def manage_party(request,pk=None):
    context = context_data(request)
    context['page'] = 'manage_user'
    context['page_title'] = 'Manage User'

    if pk :
        party = Party.objects.select_related('user').get(pk=pk)
        if party:
            if request.user.is_superuser or (request.user.staffuser if hasattr(request.user, 'staffuser') else False) and (party.user.assigned_staff.user if hasattr(party.user.assigned_staff, 'user') else None)==request.user or request.user == party.user and request.user.has_perm('accounts.change_party'):
                    context['party'] = party
            else:
                HttpResponse("You are not Authorized to Edit This Party")
        else:
            return HttpResponse("The party is invalid")        
          
    else:
        if request.user.is_superuser or (request.user.staffuser if hasattr(request.user, 'staffuser') else False) and (request.user.assigned_staff.user if hasattr(request.user.assigned_staff, 'user') else None)==request.user or  request.user.has_perm('accounts.add_party'):
            context['user_id'] = request.GET.get('user_id')
        else:
            HttpResponse("You are not Authorized to Add This Party")
    return render(request, 'accounts/manage_party.html', context)
            
@login_required
def save_party(request):
    resp = {'status': 'failed', 'msg': ''}

    if request.method == 'POST':
        post = request.POST
        party_id = post.get('id','')
        user_id = post.get('user','')
        if user_id:
            user = User.objects.get(pk=user_id)
            if party_id:
                party = Party.objects.select_related('user').get(pk=party_id)
                if request.user.is_superuser or party.user == request.user and request.user.has_perm('accounts.change_party') or (request.user.staffuser if hasattr(request.user, 'staffuser') else False) and (party.user.assigned_staff.user if hasattr(party.user.assigned_staff, 'user') else None)==request.user:
                    form = SaveParty(post, instance=party)
                else:
                    resp['msg'] = "You are not authorized to edit Party"
                    return JsonResponse(resp)
            else:
                if request.user.is_superuser or user == request.user and request.user.has_perm('accounts.add_party') or (request.user.staffuser if hasattr(request.user, 'staffuser') else False) and (user.assigned_staff.user if hasattr(user.assigned_staff, 'user') else None)==request.user:
                    form = SaveParty(post)
                else:
                    resp['msg'] = "You are not authorized to Add Party"
                    return JsonResponse(resp)
                
        if form.is_valid():
            form.save()

            if party_id == '':
                messages.success(request, "Party has been saved successfully.")
            else:
                messages.success(request, "Party has been updated successfully.")
            resp['status'] = 'success'
        else:
            for field in form:
                for error in field.errors:
                    if resp['msg'] != '':
                        resp['msg'] += '<br/>'
                    resp['msg'] += f'[{field.name}] {error}'

    else:
        resp['msg'] = "There's no data sent in the request"
    return JsonResponse(resp)


@login_required
def delete_party(request, pk=None):
    resp = {
        'status': 'failed',
        'msg': ''
    }

    if pk:
        party = Party.objects.select_related('user').filter(pk = pk)
        if party:
            if request.user.is_superuser or party.user == request.user and request.user.has_perm('accounts.add_party') or (request.user.staffuser if hasattr(request.user, 'staffuser') else False) and (party.user.assigned_staff.user if hasattr(party.user.assigned_staff, 'user') else None)==request.user:            
                if party.delete_flag == 0:
                    try:
                        party.update(delete_flag=1)
                        messages.success(request, "Party has been moved to recycle bin successfully.")
                        resp['status'] = 'success'
                    except:
                        resp['msg'] = "Deleting User Failed."
                else:
                    party.delete()
                    messages.success(request,"Party has been deleted successfully.")
                    resp['status'] = 'success'
            else:
                return HttpResponse(status=204)
        else:
            return HttpResponse(status=204)
    
    else:
        resp['msg'] = "There's no data sent in the request"

    return HttpResponse(json.dumps(resp),content_type="application/json")

@login_required
def manage_transaction(request, pk=None):
    context = context_data(request)
    context['page'] = 'manage_transaction'
    context['page_title'] = 'Manage Transaction'
    
    user_id = request.GET.get('user_id', '')
    try:
        user = User.objects.get(pk=user_id)
    except User.DoesNotExist:
        return HttpResponse(status=204)

    if pk is None:
        # Adding a new transaction
        if (request.user.is_superuser or 
            (user == request.user and request.user.has_perm('accounts.add_transaction')) or
            (hasattr(request.user, 'staffuser')  and
             user.assigned_staff.user == request.user)):
            
            context['user_id'] = user.id
            context['parties'] = Party.objects.filter(user=user, delete_flag=0)
        else:
            return HttpResponse("You are not allowed to manage Transactions. Please contact admin for further queries")
    else:
        # Editing an existing transaction
        if (request.user.is_superuser or 
            (user == request.user and request.user.has_perm('accounts.change_transaction')) or
            (hasattr(request.user, 'staffuser')  and
             user.assigned_staff.user == request.user)):
            transaction = get_object_or_404(Transaction, pk=pk)
            context['user_id'] = user.id
            transaction_data =      {'party': transaction.party.name,
                                    'description': transaction.description,
                                    'user': transaction.party.user.username,
                                    'debit': transaction.debit,
                                    'credit': transaction.credit,
                                    'date': transaction.form.created_at,
                                    'id':transaction.pk}
            
            return JsonResponse({'transaction':transaction_data})
        else:
            return HttpResponse("You are not allowed to manage Transactions. Please contact admin for further queries")

    return render(request, 'accounts/manage_transaction.html', context)

@login_required
def save_transaction(request):
    resp = {'status': 'failed', 'msg': '', 'transaction': None}

    if request.method == 'POST':

        post = request.POST
        id = post.get('id','') 
        user_id = post.get('user_id','') 
        date = post.get('date', '')
        party = post.get('name', '')
        debit = post.get('debit','')
        credit = post.get('credit','')

templates/accounts/party.html
{% extends 'base.html' %} {% load static %} {% block pageContent %} {% load customfilter %}
<style>
    .al-logo {
        height: 3em;
        width: 3em;
        object-fit: scale-down;
        object-position: center center;
    }
    
</style>
<section class="py-4">
    <div class="container"> 
        <h3 class="fw-bolder text-center">List of Parties</h3>
        <center>
            <hr class="bg-primary opacity-100" style="height:3px" width="5%">
        </center>
        <div class="card rounded-0 shadow">
            <div class="card-body">
                <div class="container-fluid">
                {% if perms.accounts.add_party or user.assigned_staff.user == request.user  %}
                    <div class="text-end mb-3">
                        <button class="btn rounded-0" type="button" id="create_new"><i class="fa fa-plus"></i> Add New Party</button>
                    </div>
                {% endif %}
                    <table class="display cell-border" class="table table-bordered table-striped" style="width:100%" id="party-tbl">
                        <thead>
                            <tr>
                                <th >#</th>
                                <th >Name</th>
                                <th >Address</th>
                                <th >Phone_number</th>
                                <th >Balance</th>
                                <th >Action</th>

                            </tr>
                        </thead>
                        <tbody>
                            {% for party in parties %}
                            <tr>
 
                                <td>{{ forloop.counter }}</td>
                                <td>{{ party.name}}</td>
                                <td>{{ party.address | check_value}}</td>
                                <td>
                                    <p class="m-0 truncate-1">{{ party.phone_number | check_value }}</p>
                                </td>
                                <td>
                                    {% with balance=party.balance %}
                                        {% if balance > 0 %}
                                            <p class="m-0 truncate-1 text-success">{{ balance }}(+)</p>
                                        {% elif balance < 0 %}
                                            <p class="m-0 truncate-1 text-danger">{{ balance | abs }}(-)</p>
                                        {% else %}
                                            <p class="m-0 truncate-1">{{ balance }}</p>
                                        {% endif %}
                                    {% endwith %}
                                </td>

                                <td>
                                
                                    <div class="dropdown">
                                        <button class="btn btn-light btn-sm rounded-0 border dropdown-toggle" type="button" id="abtn{{cat.pk}}" data-bs-toggle="dropdown" aria-expanded="false">
                                          Action
                                        </button>
                                        <ul class="dropdown-menu" aria-labelledby="abtn{{party.pk}}">
                                            {% if perms.accounts.view_party or party.user.assigned_staff.user == request.user %}
                                            <li>
                                            <a class="dropdown-item view-data-trans" href="{% url 'accounts:view-transactions' party.pk %}"><i class="fa fa-eye text-dark"></i>View Transactions</a>
                                            </li>
                                            {% endif %}
                                            {% if perms.accounts.change_party or party.user.assigned_staff.user == request.user %}
                                            <li><a class="dropdown-item edit-data" href="javascript:void(0)" data-url="{% url 'accounts:manage-party-pk' party.pk %}"><i class="fa fa-edit text-primary"></i> Edit</a></li>
                                            {% endif %}
                                            {% if perms.accounts.delete_party or party.user.assigned_staff.user == request.user %}
                                            <li><a class="dropdown-item delete-data" href="javascript:void(0)" data-url="{% url 'accounts:delete-party' party.pk %}"><i class="fa fa-trash text-danger"></i> Delete</a></li>
                                            {% endif %}
                                        </ul>
                                    </div>
                                
                                </td>
                 
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table> 
                </div>
            </div>
        </div>
    </div> 
</section>
{% endblock pageContent %} {% block ScriptBlock %}
<script>
    
    $(function() {
         $('#new_form_manage_s_p').click(function(){
            $.ajax({
                url: "{% url 'accounts:manage-sales-purchase'  %}",
                method: 'GET',
                data: {
                    'user_id': {{user.id}},
                },
                error: err =>{
                        alert("An error occured")
                    },
                success: function(resp){
                    if(resp){
                        
                        $('#myModal .modal-body').html(resp)
                        
                        $('#uni_modal').modal({
                            backdrop:'static',
                            keyboard:false,
                            focus:true
                        })
                        $("#myModal").modal('show')
                        end_loader()
                    }
                }
            });
        })
         $('#new_form_manage_transactions').click(function(){
            $.ajax({
                url: "{% url 'accounts:manage-transaction'  %}",
                method: 'GET',
                data: {
                    'user_id': {{user.id}},
                },
                error: err =>{
                        alert("An error occured")
                    },
                success: function(resp){
                    if(resp){
                        
                        $('#myModal .modal-body').html(resp)
                        
                        $('#uni_modal').modal({
                            backdrop:'static',
                            keyboard:false,
                            focus:true
                        })
                        $("#myModal").modal('show')
                        end_loader()
                    }
                }
            });
        })
        $('#new_form_product').click(function(){
            window.location.href = "{% url 'accounts:products-pk' pk=user.id %}"
        })
        $('#create_new').click(function() {
            $.ajax({
            url: "{% url 'accounts:manage-party'  %}",
            method: 'GET',
            data: {
                'user_id': {{user.id}},
            },
            error: err =>{
                    alert("An error occured")
                },
            success: function(resp){
                if(resp){
                    $('#uni_modal .modal-title').html("Add New Party")
                    $('#uni_modal .modal-body').html(resp)
                    
                    $('#uni_modal').modal({
                        backdrop:'static',
                        keyboard:false,
                        focus:true
                    })
                    $("#uni_modal").modal('show')
                    end_loader()
                }
            }
});
             
        })
            // Attach click event to the view-data link

        
        $('.edit-data').click(function() {
            uni_modal("<i class='fa fa-edit'></i> Edit Party Details", $(this).attr('data-url'))
        })
        $('.view_image').click(function() {
            var img = $(this).attr('data-img-url')
            $('#viewer_modal #img-viewer-field').attr('src', img)
            $('#viewer_modal').modal('show')
        })
        $('.delete-data').click(function() {
            _conf("Are you sure to delete this party?", 'delete_party', ["'" + $(this).attr('data-url') + "'"])
        })
        $('#party-tbl').find('td, th').addClass('px-2 py-1 align-middle')
        var dataTable = $('#party-tbl').DataTable({
            layout: {
                    topStart: {
                        buttons: [
                        {
                            extend: 'print',
                            title: '',
                            autoPrint: true,
                            customize: function (win) {
                                $(win.document.body).find('th:last-child').text('Received');
                                $(win.document.body).find('td:last-child').empty();
                            }
                        },
                        {
                                extend: 'pdfHtml5',
                                title:"",
                                exportOptions: {
                                    columns: [ 0, 1, 2, 3,4 ],
                             

                                },
                                customize: function (doc) {
                                    doc.styles['table'] = {alignment:'center'};
                                    doc.content[0].table.widths = [ '5%',  '25%', '25%', '18%','15%','12%'];
                                    processDoc(doc);
                                   addExtraColumn(doc);
                                    doc.content[0].layout = 'lightHorizontalLines'  
                                }
                            }
                        ]  
                }
            }, 
            responsive: {
                details: {
                    type: 'column',
                    target: 'tr'
                }
            },
            columnDefs: [
                {
                    orderable: false,
                    targets: [1,2,3,4,5]
                },
                { "width": "120px", "targets": 3 }, // Set width for the first column
                { "width": "90px", "targets": 4 },   // Set width for the third column
                { "width": "40px", "targets": 5 },
                { responsivePriority: 1, targets: 1 },
                { responsivePriority: 2, targets: -1 },
                { responsivePriority: 3, targets: 4 },
            ],
            order: [[0, 'asc']],
            lengthMenu: [
                [25, 50, 100, -1],
                [25, 50, 100, "All"]
            ],
        })
        var hideColumnIndex = 0;
        var column = dataTable.column(hideColumnIndex);
        column.visible(false);

})

    function delete_party(url) {

        var _this = $('#confirm_modal .modal-body')
        $('.err-msg').remove();
        var el = $('<div>')
        el.addClass("alert alert-danger err-msg")
        el.hide()
        start_loader()
        $.ajax({
            headers: {
                "X-CSRFToken": "{{csrf_token}}"
            },
            url: url,
            dataType: 'JSON',
            error: err => {
                console.log(err)
                alert("an error occurred.")
                end_loader()
            },
            success: function(resp) {
                if (resp.status == 'success') {
                    location.reload()
                } else if (!!resp.msg) {
                    el.html(resp.msg)
                    _this.prepend(el)
                    el.show()
                } else {
                    el.html("An error occurred")
                    _this.prepend(el)
                    el.show()
                }
                end_loader()
            }

        })
    }
    function processDoc(doc) {
    pdfMake.fonts = {
      Roboto: {
        normal: 'Roboto-Regular.ttf',
        bold: 'Roboto-Medium.ttf',
        italics: 'Roboto-Italic.ttf',
        bolditalics: 'Roboto-MediumItalic.ttf'
      },
      arial: {
        normal: 'arial.ttf',
        bold: 'arial.ttf',
        italics: 'arial.ttf',
        bolditalics: 'arial.ttf'
      },
      noto:{
        normal: 'noto.ttf',
        bold: 'noto.ttf',
        italics: 'noto.ttf',
        bolditalics: 'noto.ttf'
      }
    };
    // modify the PDF to use a different default font:
    doc.defaultStyle.font = "noto";
    var i = 1;
    }
    function addExtraColumn(pdf) {
    pdf.content[0].table.body.forEach(function(row, idx) { 
      let newCell = structuredClone(row[0]);
      newCell.text = idx === 0 ? "Received" : "";
      row.push( newCell );
    })
  };
</script>
{% endblock ScriptBlock %}